Complete the implementation of `calc_tabulated_physics_step`
celeritas-project/celeritas pull request #154
Opened 2021-02-19 03:34 UTC by amandalund

This add the missing pieces to `calc_tabulated_physics_step` in PhysicsStepUtils.hh (for #125):
  * Add macroscopic cross section calculators for the photoelectric effect and positron annihilation models
  * Hardwire those processes to compute macro xs on the fly when calculating step length

2021-02-19 21:27 UTC, sethrj requested changes
Excellent, Amanda! I think the way of pulling in "hardwired" data needs to be improved just a bit, but it should be a minor change, and everything else is very well done.

2021-02-19 23:11 UTC, amandalund commented on src/physics/base/PhysicsParams.cc
> +    }
Ahh thanks, that's definitely a cleaner way of doing it.

2021-02-22 22:27 UTC, amandalund commented
@sethrj I think I addressed all your comments here, but let me know if I'm missing anything or need to tweak the hardwiring of the models at all.

2021-02-23 00:13 UTC, sethrj approved these changes
Very nice!

2021-02-23 00:14 UTC, merged