Extend Collection documentation and add doxygen main page
celeritas-project/celeritas pull request #193
Opened 2021-03-21 16:02 UTC by sethrj

2021-03-21 17:01 UTC, amandalund requested changes

2021-03-21 23:27 UTC, sethrj commented on src/physics/base/ModelInterface.hh
> +    RngStateData<Ownership::reference, MemSpace::device>      rng;
Whoops! This got pulled in from the other branch I was working on 😳

2021-03-21 23:52 UTC, sethrj commented on src/base/Collection.hh
> +a
This line was the only place I could find -- were there others?

2021-03-22 00:02 UTC, amandalund commented on src/base/Collection.hh
> +a
138 too, but no big deal.

2021-03-22 00:03 UTC, amandalund approved these changes
Thanks Seth!

2021-03-22 00:13 UTC, sethrj commented on src/base/Collection.hh
> +a
Oh, that was me manually breaking. I tend not to reflow paragraphs of doxygen/tex/markdown because it makes diffs harder to read.

2021-03-22 00:14 UTC, merged