Minor changes to magnetic field in preparation for AlongStep integration
celeritas-project/celeritas pull request #428
Opened 2022-05-18 10:50 UTC by sethrj

The main refactoring here is the ability to create a field propagator much more simply:
```c++
    UniformField field({0, 0, test.field_value});
    auto propagate = make_mag_field_propagator<DormandPrinceStepper>(
        field, driver_options, particle_track, &geo_track);
```

2022-05-18 14:52 UTC, whokion commented
@sethrj there are several compilation errors from cu files.

2022-05-18 16:09 UTC, whokion requested changes
Please fix remaining compilation errors from UserParamField.test.cu
and then it should be good to go.

2022-05-18 19:43 UTC, sethrj commented on test/celeritas/field/FieldDriver.test.cu
> +        field_params,
Sorry copy-paste error and I didn't test the cuda code .. should have left this as draft

2022-05-23 07:54 UTC, sethrj commented
@whokion I fixed the bug—unintentional dangling reference. Thanks for the review!

2022-05-23 18:05 UTC, merged