Add templated cube() to Algorithms.h
celeritas-project/celeritas pull request #68
Opened 2020-11-05 18:41 UTC by vpascuzz

`std::pow(a, 3)` takes some 245 operations. A templated function `cube(const T& a)` is added in this commit that instead uses `a * a * a` which takes only 9 operations.

2020-11-05 18:48 UTC, sethrj commented
Looks good! Good idea giving it an independent function. Looking at your MR, I realize I didn't add any tests for the previous one-line algorithms in there, which would be a good idea even if they are dead simple. Would you create a new `Algorithms.test.cc` and add tiny tests for min/max/cube, or would you prefer that I do that since it was my oversight?

2020-11-05 19:14 UTC, vpascuzz commented
> Would you create a new `Algorithms.test.cc` and add tiny tests for min/max/cube, or would you prefer that I do that since it was my oversight?

Sure, I can do this -- no problem. You suggest adding to the same PR, or a separate one?

2020-11-05 20:08 UTC, sethrj commented
Same PR would be great -- I was going to ask for a one-line unit test when I realized that I'd not done any myself for the min/max 😅

2020-11-09 17:28 UTC, vrpascuzzi commented
Changes unrelated to failed checks

2020-11-09 18:26 UTC, sethrj requested changes
> Changes unrelated to failed checks

I think they are.... it looks like you might've forgotten to commit and upload the test file? 😬 

```
CMake Error at cmake/CeleritasAddTest.cmake:308 (add_executable):
209  Cannot find source file:
210
211    base/Algorithms.test.cc
212
213  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
214  .hpp .hxx .in .txx
215Call Stack (most recent call first):
216  test/CMakeLists.txt:76 (celeritas_add_test)
217
218
219
```

2020-11-09 18:35 UTC, vrpascuzzi commented on src/base/Algorithms.hh
> +CELER_CONSTEXPR_FUNCTION const T cube(const T& a)
D'oh! Thanks -- all better.

2020-11-09 21:02 UTC, sethrj reviewed
Two tiny formatting issues if you'll allow me to quibble.

2020-11-09 21:02 UTC, sethrj commented on src/base/Algorithms.hh
> +
Tiny consistency quibble (this is a carryover of how Shift and its stylistic progenitors were formatted) but there shouldn't be a newline here.

2020-11-09 21:41 UTC, sethrj approved these changes
Thanks @vrpascuzzi !

2020-11-09 21:51 UTC, merged