Add RectArrayTracker class
celeritas-project/celeritas pull request #758
Opened 2023-05-12 18:14 UTC by elliottbiondo

This PR implements RectArrayTracker, a class for tracking on an axis-aligned rectilinear grid. While the intent is to use this class core loading in a reactor context, it can also be used for Cartesian mesh tallies. This PR also includes utility classes for indexing into a N-dimensional hyperslab and also ragged right arrays.

2023-05-12 18:38 UTC, elliottbiondo commented
@sethrj this is ready for your review

2023-05-16 12:09 UTC, sethrj requested changes
Pausing for discussion before continuing to the RectArrayTracker itself

2023-05-16 12:09 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +    using index_type = T;
Should be `size_type`. The `Coords` should have the same data type, and even though this could override the default `celeritas::size_type` (which in practice I don't think it will?) we should avoid `index_type` since it was removed from `mdspan`, which my original implementation predated.

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p0009r18.html

2023-05-16 12:09 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +    }
```suggestion
    size_type result = coords[0];
    for (size_type i = 1; i < N; ++i)
    {
        result = dims_[i] * result + coords[i];
    }
```

2023-05-16 12:09 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +{
```suggestion
{
    CELER_EXPECT(index <= this->size());
```

2023-05-16 12:09 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +    for (int i = dims_.size() - 1; i >= 0; i--)
Mixing signed and unsigned arithmetic should be avoided. Also you should be able to terminate the loop earlier to avoid the last access of `dims_` and the divmod.

2023-05-16 12:09 UTC, sethrj commented on src/corecel/data/RaggedRightIndexer.hh
> +    using index_type = T;
```suggestion
    using size_type = T;
```
same comment as above: maybe eliminate the templating on integer type for the time being?

2023-05-16 12:09 UTC, sethrj commented on src/corecel/data/RaggedRightIndexer.hh
> +template<class T, size_type N>
The template parameter is a little confusing because it's for a *fixed* outer size and a *variable* inner size. Usually ragged data structures are variable in both.

The N parameter is also confusing, since this class is fixed to a rank of 2, in contrast to the Hyperslab Indexer whose *rank* is N.

2023-05-16 12:09 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +    Coords dims_;
I wonder if we should do something similar to rotations: make this a const reference to existing data, and separate the "action" and "inverse action" into different functors?

2023-05-16 12:09 UTC, sethrj commented on src/corecel/data/RaggedRightIndexer.hh
> +    ragged_indices(index_type flattened_index) const;
If this is to be an `Indexer` like the HS indexer the functions should have the same names.

2023-05-16 12:09 UTC, sethrj commented on src/corecel/data/RaggedRightIndexer.hh
> +}
Since this is to be reused on GPU with presumably immutable data, I think it'd be better to define a `RaggedRightData` class that precalculates these offsets rather than looping through it every time on construction.

2023-05-16 12:09 UTC, sethrj commented on src/corecel/data/RaggedRightIndexer.hh
> +    }
Define a `find_lower_bound` (i.e. operation of `lower_bound` with performance of `find`) in `corecel/math/Algorithms.hh`. It should be a for loop in the range `0, N-1` to avoid going off the end (and doing one less comparison).

2023-05-16 12:09 UTC, sethrj commented on src/corecel/grid/NonuniformGrid.hh
> +                                                  // "sorted"
What version of clang-format are you using? The existing formatting is correct in mine (15.0.6).

2023-05-16 12:09 UTC, sethrj commented on src/corecel/grid/NonuniformGrid.hh
> +    struct result_type
The class name shoudn't be `result_type` because that's exclusively for the return result of `operator()` classes. 

The `find_interp` function defines an index + fraction and returns a small struct named `FindInterp`. So maybe `FindEdge`? (Or maybe change both use cases?)

2023-05-16 12:09 UTC, sethrj commented on src/corecel/grid/NonuniformGrid.hh
> +        bool on_edge;
We try to provide default values for all our structs for safety:
```suggestion
        size_type cell{};  //!< [0, span.size())
        bool on_edge{};
```

2023-05-16 12:09 UTC, sethrj commented on src/corecel/grid/NonuniformGrid.hh
> +        bool operator==(result_type const& other) const
This will need to be device compatible:
```suggestion
        CELER_FUNCTION bool operator==(result_type const& other) const
```

2023-05-16 12:09 UTC, sethrj commented on src/corecel/grid/NonuniformGrid.hh
> +    using Data = Span<value_type const>;
This typedef isn't used publicly and is also a bit confusing as most of the `Data` classes are more complex structs.

2023-05-16 12:09 UTC, sethrj commented on src/corecel/grid/NonuniformGrid.hh
> +        // to previous bin
Your clang-format is definitely acting up...

2023-05-16 12:09 UTC, sethrj commented on src/corecel/grid/NonuniformGrid.hh
> +NonuniformGrid<T>::find_edge(value_type value) const
I'm really not sure how much value this new struct and extra function has versus
```c++
   size_type index = grid.find(value);
   bool edge = grid[index] == value;
```
Aside from an extra `CELER_EXPECT` which gets optimized out and the access of `*(ptr + index)` instead of `*value_ptr`, which even use the same single instruction in PTX and most machine languages, the extra `find_edge` adds nothing that I can see.

Doing that explicitly also makes the "edge case" clear that this function will *not* behave any differently for the final upper bound than the other find/access methods.

2023-05-16 12:09 UTC, sethrj commented on src/orange/OrangeData.hh
> +
There will never be a `background` for Arrays: every cell in the valid region is filled with another universe.

2023-05-16 12:09 UTC, sethrj commented on test/corecel/data/HyperslabIndexer.test.cc
> +#endif
```suggestion
TEST(HyperslabIndexerTest, TEST_IF_CELERITAS_DEBUG(error))
{
    EXPECT_THROW((HyperslabIndexer<size_type, 3>({2, 0, 3})), DebugError);
}
```
This way the test is compiled either way but just disabled if debugging is.

2023-05-16 12:09 UTC, sethrj commented on test/corecel/grid/NonuniformGrid.test.cc
> +#endif
Use C++ `if` instead of C preprocessor macros unless the embedded code is invalid (e.g. calling an external library that isn't `#include`d).
```suggestion
    if (CELERITAS_DEBUG)
    {
        EXPECT_THROW(grid.find(-1), DebugError);
    }
```

2023-05-16 15:26 UTC, elliottbiondo commented on src/corecel/data/HyperslabIndexer.hh
> +    using index_type = T;
So this:

```
    using size_type = T;
    using Coords = Array<size_type, N>;
```

I am not sure what you mean by "The Coords should have the same data type"? The where using index_type to begin with.

2023-05-16 15:29 UTC, elliottbiondo commented on src/corecel/data/HyperslabIndexer.hh
> +    using index_type = T;
I mean, why not just using `T` throughout the class, or hard code `size_type` as the index type? Overwriting celeritas::size_type seems needlessly confusing.

2023-05-16 15:57 UTC, elliottbiondo commented on src/corecel/data/RaggedRightIndexer.hh
> +    using index_type = T;
So eliminate the template parameter `T`?

2023-05-16 16:06 UTC, elliottbiondo commented on src/corecel/grid/NonuniformGrid.hh
> +                                                  // "sorted"
`clang-format version 15.0.4` on wildstyle:

`/opt/spack-20221016/opt/spack/linux-rhel8-cascadelake/clang-12.0.1/llvm-15.0.4-sek4npj2bmoo7fv46fmjostznjel7qk5/bin/clang-format`

2023-05-16 16:13 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +    using index_type = T;
Yeah either remove T and use the default size type, or override it within the class.

2023-05-16 17:07 UTC, elliottbiondo commented on src/corecel/data/RaggedRightIndexer.hh
> +template<class T, size_type N>
If there is a use case, we can expand to more dimensions. I feel like there will be, given how important serialization is. So far the only use cases the need this are both 2D: RectArray surfaces and UniverseIndexer (to be refactored). Do you have a suggestion for a template parameter to use other than `N`?

2023-05-16 17:24 UTC, elliottbiondo commented on src/corecel/data/HyperslabIndexer.hh
> +    Coords dims_;
This was intended to be a const ref (fixed now).

I don't see what rotation code you are referencing? What is the motivation for refactoring this --- it's a straightforward 3-method class.

2023-05-16 17:30 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +    Coords dims_;
Sorry I meant the `Translation` class (precursor to `Transformation`). The motivation is that if you have a class with only a single method, the name is trivial, whereas with two you have to look it up. So if you had `HyperslabIndexer`, you just need `HyperslabIndexer index{data}; size_type i = index(xyz);` and if you have `HyperslabInverseIndexer` its meaning would be obvious.

2023-05-16 17:32 UTC, sethrj commented on src/corecel/data/RaggedRightIndexer.hh
> +template<class T, size_type N>
I totally agree it's not worth complicating this into D>2. But my question is more about why it's templated with fixed `N=3`? The universe indexer isn't going to be a fixed `N`; it'll have runtime `N=`number of universes.

2023-05-16 17:35 UTC, sethrj commented on src/corecel/grid/NonuniformGrid.hh
> +                                                  // "sorted"
Could you have possibly have modified this line, or used some weird VSCode extension? Running `.../clang-format -i src/corecel/grid/NonuniformGrid.hh` results in no changes, so this line and a couple others have been borked somehow.

2023-05-16 18:49 UTC, elliottbiondo commented on src/corecel/data/RaggedRightIndexer.hh
> +template<class T, size_type N>
It's not fixed `N=3`. Where are you looking?

2023-05-16 18:53 UTC, sethrj commented on src/corecel/data/RaggedRightIndexer.hh
> +template<class T, size_type N>
Sorry, I meant it's *used* so far with compile-time N=3, but in practice it'll have to be used with a runtime dynamic N.

2023-05-16 22:03 UTC, elliottbiondo commented on src/corecel/data/RaggedRightIndexer.hh
> +template<class T, size_type N>
Ah, sorry I see what you're saying. Well, I suppose I won't be able to refactor UniverseIndexer, but that isn't really a priority.

2023-05-16 22:22 UTC, elliottbiondo commented on src/corecel/grid/NonuniformGrid.hh
> +                                                  // "sorted"
I didn't touch these lines and I am editing via vim. I am not sure what is going on.

2023-05-16 22:24 UTC, elliottbiondo commented on src/corecel/data/RaggedRightIndexer.hh
> +template<class T, size_type N>
I don't see a simple way of dynamically sizing this class. Since we don't have an immediate need for dynamic sizing I'd say we should punt on this.

2023-05-16 23:39 UTC, elliottbiondo commented on src/corecel/grid/NonuniformGrid.hh
> +                                                  // "sorted"
Strange that this isn't failing the clang-format part of CI...

2023-05-17 00:13 UTC, sethrj commented on src/corecel/grid/NonuniformGrid.hh
> +                                                  // "sorted"
There's not a clang format CI  the given formatting passes but it's weird that the lines changed

2023-05-17 00:21 UTC, elliottbiondo commented on src/corecel/grid/NonuniformGrid.hh
> +NonuniformGrid<T>::find_edge(value_type value) const
I implemented this as we discussed. I will revert the changes to this file.

2023-05-17 00:48 UTC, elliottbiondo commented on src/corecel/data/RaggedRightIndexer.hh
> +    }
When you way "performance of find" I assume you mean binary search. It looks like the implementation of lower_bound in celeritas is already using binary search, so why not just use that?

2023-05-17 01:00 UTC, sethrj commented on src/corecel/data/RaggedRightIndexer.hh
> +template<class T, size_type N>
Yeah, just make it a detail class for now since it's not very reusable as is?

2023-05-17 02:23 UTC, sethrj commented on src/corecel/data/RaggedRightIndexer.hh
> +    }
Nah I meant that like your loop above, `find` works in linear time `$O(N)$` but tends to have a much smaller constant in front of it than the binary search's `$O(log N)$`, so ends up being faster for small N.

2023-05-17 15:26 UTC, elliottbiondo commented on src/corecel/data/RaggedRightIndexer.hh
> +    }
How about `lower_bound_linear` to be more explicit w.r.t. the difference with `lower_bound`?

2023-05-17 15:47 UTC, elliottbiondo commented
@sethrj this is ready for another look

2023-05-28 15:58 UTC, sethrj requested changes

2023-05-28 15:58 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +{
Since this is in a header, it's going to be compiled in every translation unit that includes it. Move to `detail/HyperslabIndexerImpl.hh`.

2023-05-28 15:58 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +hyperslab_size(celeritas::Array<celeritas::size_type, N> dims)
```suggestion
hyperslab_size(celeritas::Array<celeritas::size_type, N> const& dims)
```

2023-05-28 15:58 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +{
```suggestion
{
    CELER_EXPECT(coords[0] < dims_[0]);
```

2023-05-28 15:58 UTC, sethrj commented on src/corecel/data/HyperslabIndexer.hh
> +    {
```suggestion
    {
        CELER_EXPECT(coords[i] < dims_[i]);
```

2023-05-28 15:58 UTC, sethrj commented on src/corecel/data/detail/RaggedRightIndexer.hh
> +class RaggedRightIndexerData
Data should be structs with public data. Use a `static` member helper function to construct the `Offsets`. See e.g. `UniformGridData`.

2023-05-28 15:58 UTC, sethrj commented on test/CMakeLists.txt
> +celeritas_add_test(corecel/data/detail/RaggedRightIndexer.test.cc GPU)
Since these tests don't call any GPU functions they shouldn't have the GPU tag.

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +    CELER_FUNCTION RectArrayRecord const& record() const { return record_; }
I don't think this accessor is needed any more (or its UnitTracker analog)

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +    surface_indexer_data_ = SurfaceIndexerData(sizes);
Since the RectArrayTracker is effectively temporary, we're going to be recreating these values a *lot* (and that's a lot of memory accesses). I think you should precalculate all this constructor data inside the RectArrayRecord.

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +            return {{}, {}};
```suggestion
            return {};
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +        }
I think these sort of "nested exception" cases usually look better by returning early and keeping the "normal case" logic at the same depth rather than increasingly nested:

```suggestion
        size_type index = grid.find(pos);
        if (grid[index] == pos)
        {
            // Initialization exactly on an edge is prohibited
            return {};
        }
        coords[to_int(ax)] = index;
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +    auto ax_idx = sii(state.surface.id().unchecked_get())[0];
Give a function-like object instance a function-like name:
```suggestion
    SurfaceInverseIndexer to_axis_edge(surface_indexer_data_);
    auto ax_idx = to_axis_edge(state.surface.id().unchecked_get())[0];
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +        // crossimg out
```suggestion
        // Crossing out
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +    auto coords = vii(volid.unchecked_get());
Since it's only executed once, you could do...
```suggestion
    auto coords = VolumeInverseIndexer{dims_}(volid.unchecked_get());
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +            min_dist = min(min_dist, fabs(pos[to_int(ax)] - target));
```suggestion
            min_dist = min(min_dist, std::fabs(pos[to_int(ax)] - target));
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +CELER_FUNCTION auto RectArrayTracker::normal([[maybe_unused]] Real3 const& pos,
```suggestion
CELER_FUNCTION auto RectArrayTracker::normal(Real3 const&,
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +    size_type ax = sii(surf.get())[0];
Since the "surface inverse indexer" seems exclusively to find the axis, it deserves a member function
```c++
Axis find_surface_axis(SurfaceId s);
```
(or return `int` rather than having to use `to_int(axis)` later)

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +            = params_.reals[record_.grid[to_int(ax)]][target_coord];
Prefer accessing the data through the interface classes:
```suggestion
        auto target_value = this->make_grid(ax)[target_coord];
```
where
```c++
Grid make_grid(Axis) const
{
    return Grid(record_.grid[to_int(ax)], params_.reals);
}
```
which you can use in a couple of places.

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +            = (target_value - static_cast<double>(state.pos[to_int(ax)]))
```suggestion
        real_type dist
            = (target_value - static_cast<real_type>(state.pos[to_int(ax)]))
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +        if (dir == 0.0)
```suggestion
        if (dir == real_type(0))
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +    Real3 normal{0., 0., 0.};
```suggestion
    Real3 normal{0, 0, 0};
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +        if (dist > 0 && dist < result.distance)
```suggestion
        if (dist > 0 && is_valid(dist) && dist < result.distance)
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +    return (is_valid(result.distance)) ? result : Intersection{};
```suggestion
    return result;
```

2023-05-28 15:58 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +        auto target_coord = coords[to_int(ax)] + static_cast<int>(dir > 0.);
```suggestion
        auto target_coord = coords[to_int(ax)] + static_cast<int>(dir > 0);
```

Remember `0.` is a double literal, so I think comparisons (and certainly operations) will upcast the float.

2023-05-28 15:58 UTC, sethrj commented on test/corecel/data/HyperslabIndexer.test.cc
> +    HyperslabInverseIndexer<2> hii({3, 4});
Do you think these would be more readable:
```suggestion
    HyperslabIndexer<2> to_index({3, 4});
    HyperslabInverseIndexer<2> from_index({3, 4});
```
(or `to_coords` or `index_to_coords`)?

Also you're referencing a temporary during this construction, which is an error: make sure to do
```c++
  Data const dims{3, 4};
  HyperslabIndexer<2> to_index(dims);
```

2023-05-28 15:58 UTC, sethrj commented on test/corecel/data/HyperslabIndexer.test.cc
> +    HyperslabInverseIndexer<4> hii({4, 6, 3, 2});
Same reference-after-use

2023-05-28 15:58 UTC, sethrj commented on test/corecel/data/HyperslabIndexer.test.cc
> +                for (size_type l : range(2))
Please avoid using `l` as a single-letter variable due to its similarity to `1` 😅

2023-05-30 16:10 UTC, elliottbiondo commented on src/orange/univ/RectArrayTracker.hh
> +CELER_FUNCTION auto RectArrayTracker::normal([[maybe_unused]] Real3 const& pos,
Delete `pos`?

2023-05-30 16:39 UTC, sethrj commented on src/orange/univ/RectArrayTracker.hh
> +CELER_FUNCTION auto RectArrayTracker::normal([[maybe_unused]] Real3 const& pos,
You can just remove the identifier and it'll work. You need the types for the function signature, but if you aren't using the variable locally, just delete `pos`.

2023-05-30 22:13 UTC, elliottbiondo commented
@sethrj this should be ready, pending CI

2023-05-31 13:57 UTC, sethrj approved these changes

2023-06-01 14:55 UTC, elliottbiondo commented
@sethrj I fixed some minor CI issues. This should be ready to merge.

2023-06-01 15:02 UTC, sethrj approved these changes

2023-06-01 15:02 UTC, merged