Add option to transport particles in Celeritas when no processes are assigned
celeritas-project/celeritas pull request #782
Opened 2023-05-30 18:42 UTC by stognini

This PR adds the option to transport a particle to the next geometry boundary until it escapes the world volume when no processes are assigned to it. This replicates Geant4's behavior when only the `G4Transportation` process is added to a given particle. Since Celeritas has no equivalent `transportation` process, this is achieved by tweaking the pre- and along-step implementations. If no processes are assigned to a given particle and the transport option is on:
- Pre-step sets the step limit to infinity.
- Along-step sets the interaction mfp to infinity and lets the already existing code to move the particle to boundary and cross it.

2023-05-31 13:13 UTC, sethrj requested changes

2023-05-31 13:13 UTC, sethrj commented on src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
> +    GPO_LOAD_OPTION(relaxation);
This is duplicated with `relaxation` above: likely some merge conflict resolution

2023-05-31 13:13 UTC, sethrj commented on src/celeritas/ext/GeantPhysicsOptions.hh
> +           && a.relaxation == b.relaxation
```suggestion
```

2023-05-31 13:13 UTC, sethrj commented on src/celeritas/ext/GeantImporter.cc
> +    ProcessFilter include_process{selection.processes};
I think you can revert the changes to this file?

2023-05-31 13:13 UTC, sethrj commented on src/celeritas/global/alongstep/detail/AlongStepImpl.hh
> +            phys.interaction_mfp(numeric_limits<real_type>::infinity());
I don't think this should be in the along-step process. The infinite free path should be sampled during pre-step.

2023-05-31 13:13 UTC, sethrj commented on src/celeritas/io/ImportModel.hh
> +    unknown [[deprecated]] = other,  // remove in v0.4
Accidental addition from conflict resolution

2023-05-31 13:39 UTC, sethrj requested changes
This also needs unit tests: it would have helped you a lot to add one before trying to validate your branch in your helper app. Update `celeritas/SimpleTestBase.cc` to use the null process and add a test to Stepper.test.cc.

2023-05-31 13:39 UTC, sethrj commented on src/celeritas/phys/detail/PreStepActionImpl.hh
> +        sim.reset_step_limit();
Instead of this, why not set to `{geo boundary, numeric_limits::max}`? I think then you wouldn't have to make any changes to the along-step kernel.

2023-05-31 13:39 UTC, sethrj commented on src/celeritas/phys/detail/PreStepActionImpl.hh
> +            = track.core_scalars().along_step_neutral_action;  // Needed?
Yeah it's needed.

2023-06-02 14:43 UTC, sethrj approved these changes
OK thanks for iterating with me on that! I think this is an easy "hack" for a good capability.

2023-06-02 15:00 UTC, stognini commented
Thanks for reviewing it. I think this way we replicate the behavior of G4 with as little code as possible---which seems cleaner than a fake process. It should work with any fake particle that has no assigned processes to it (like a celeritino) and we can add an option to kill and deposit energy locally for real particles in the future.

2023-06-03 12:42 UTC, merged