Refactor positron annihilation, Rayleigh scattering, and Seltzer-Berger models
celeritas-project/celeritas pull request #786
Opened 2023-05-31 19:55 UTC by stognini

This PR is a follow-up of #783 and refactors `EPlusGGModel`, `RayleighModel`, and `SeltzerBergerModel`.

2023-05-31 20:31 UTC, sethrj requested changes

2023-05-31 20:31 UTC, sethrj commented on src/celeritas/em/model/EPlusGGModel.cu
> +        InteractionApplier{EPlusGGExecutor{this->host_ref()}});
Should be `this->device_ref()`. The use of `host_ref` in the `.cu` file I wrote was a mistake, as we discussed with Philippe. It returns the same data type for now so probably shouldn't matter?

2023-05-31 20:31 UTC, sethrj commented on src/celeritas/em/model/RayleighModel.cu
> +        InteractionApplier{RayleighExecutor{this->host_ref()}});
Same comment about device data

2023-05-31 20:31 UTC, sethrj commented on src/celeritas/em/model/SeltzerBergerModel.cu
> +        InteractionApplier{SeltzerBergerExecutor{this->host_ref()}});
Same

2023-05-31 20:39 UTC, sethrj approved these changes
LGTM! I'll wait on a successful pipeline. Thanks!

2023-06-01 17:04 UTC, sethrj commented
@stognini can you make sure this compiles on wildstyle before your next push?

2023-06-01 17:10 UTC, stognini commented
> @stognini can you make sure this compiles on wildstyle before your next push?
The last commit was actually from wildstyle and it passed all tests...

2023-06-01 17:11 UTC, sethrj commented
Sorry @stognini , that was totally on me... I messed up the merge of develop into the branch 🤦

2023-06-01 19:15 UTC, merged