cmake-rdc: add support for MODULE library.
celeritas-project/celeritas pull request #848
Opened 2023-07-10 18:41 UTC by pcanal

And a few cleanups (See STREQUAL usage)

2023-07-10 20:06 UTC, sethrj approved these changes
Looks good to me, I guess it was quite a simple change after all. You said that replacing this with the standalone https://github.com/pcanal/CudaRDCExercise will happen in a separate commit?

2023-07-10 20:10 UTC, sethrj commented on cmake/CeleritasLibrary.cmake
> +        if (NOT ${_need_to_use_shared_runtime} AND _lib_runtime_setting STREQUAL "Shared")
```suggestion
        if (NOT _need_to_use_shared_runtime AND _lib_runtime_setting STREQUAL "Shared")
```

2023-07-10 20:10 UTC, sethrj commented on cmake/CeleritasLibrary.cmake
> +  if (_ADDLIB_PARSE_MODULE)
```suggestion
  if(_ADDLIB_PARSE_MODULE)
```

2023-07-10 20:10 UTC, sethrj commented on cmake/CeleritasLibrary.cmake
> +        arg STREQUAL "MODULE"
Maybe simplify to `arg MATCHES "^[A-Z_]+$"`? All source files will have an extension.

2023-07-11 08:56 UTC, drbenmorgan approved these changes
All looks good to me! Have tested on the FullSimLight module library that exposed the problem and confirmed the changes here resolve the issue, so good to go on that side of things.

2023-07-11 08:56 UTC, drbenmorgan commented on cmake/CeleritasLibrary.cmake
> +    if (_iscudafile STREQUAL "CUDA")
```suggestion
    if(_iscudafile STREQUAL "CUDA")
```

2023-07-11 12:16 UTC, sethrj requested changes
I noticed a couple of places that could use fixing/improving

2023-07-12 00:30 UTC, pcanal commented
> You said that replacing this with the standalone [pcanal/CudaRDCExercise](https://github.com/pcanal/CudaRDCExercise) will happen in a separate commit?

A separate PR as it is semantically unrelated.

2023-07-12 00:35 UTC, pcanal commented on cmake/CeleritasLibrary.cmake
> +        arg STREQUAL "MODULE"
Yes, I could do that .. note that this code is literally inspired by Kitware's code in FindCUDA.mk: Kitware/CMake@b8b53db/Modules/FindCUDA.cmake#L1327

2023-07-12 01:41 UTC, sethrj commented
So is the replacement of "x" which made this harder to review 😬

2023-07-12 19:02 UTC, sethrj commented on cmake/CeleritasLibrary.cmake
> +        arg STREQUAL "MODULE"
The FindCUDA is *very* old but you have a point... I'm just concerned about more library arguments being added by kitware.

2023-07-12 19:03 UTC, sethrj approved these changes

2023-07-12 19:03 UTC, merged