Use BIH for cross_boundary calls
celeritas-project/celeritas pull request #909
Opened 2023-08-25 21:47 UTC by elliottbiondo

This PR modifies `SimpleUnitTracker::cross_boundary` to use the bounding interval hierarchy (BIH) when there are more than 2 neighbor cells to search (excluding the current cell). With this PR, bumped bounding boxes become strictly necessary for tracking. Likewise, a `calc_bumped` function has been added to `BoundingBoxUtils` to perform this bump prior to constructing the BIH.

2023-08-26 13:08 UTC, sethrj requested changes

2023-08-26 13:08 UTC, sethrj commented on src/orange/BoundingBoxUtils.hh
> +        lower[ax] = std::nextafter(static_cast<T>(bbox.lower()[ax]),
These are only constexpr since C++23 so I don't think this function can be constexpr.

2023-08-26 13:08 UTC, sethrj commented on src/orange/detail/UnitInserter.cc
> +                calc_bumped<fast_real_type, real_type>(inp.volumes[i].bbox));
The way we set up the function signature, the second template argument can be inferred:
```suggestion
            bboxes.push_back(calc_bumped<fast_real_type>(inp.volumes[i].bbox));
```

2023-08-26 13:08 UTC, sethrj commented on test/orange/BoundingBoxUtils.test.cc
> +{
I'd change all the code here to be specifically float/double rather than real/fast_real.

2023-08-26 13:08 UTC, sethrj commented on src/orange/univ/SimpleUnitTracker.hh
> +        return detail::LogicEvaluator(vol.logic())(logic_state.senses);
You're saving a pointer to a temporary here 😱

Instead, just make a local `OnLocalSurface on_surface`, and 
```suggestion
        if (detail::LogicEvaluator(vol.logic())(logic_state.senses))
        {
            // Inside: find and save the local surface ID, and end the search
            on_surface = surface(vol, logic_state.face);
            return true;
        }
        return false;
```

2023-08-26 13:08 UTC, sethrj commented on test/orange/BoundingBoxUtils.test.cc
> +
```suggestion
```

2023-08-28 14:52 UTC, elliottbiondo commented
@sethrj pending CI this should be ready

2023-08-28 14:57 UTC, sethrj approved these changes
Looks great! Easy, clean, and hopefully much faster for pseudoarrays.

2023-08-28 18:19 UTC, merged