Implement UniverseVisitor for multiply-dispatched tracker types
celeritas-project/celeritas pull request #959
Opened 2023-09-25 20:35 UTC by elliottbiondo

This PR adds a `UniverseVisitor` class to facilitate multiply-dispatched tracker types (i.e., SimpleUnitTracker, RectArrayTracker). This functionality can be "hooked up" by replacing tracker calls like so:

```
auto tracker = this->make_tracker(uid);
auto tinit = tracker.initialize(local);
```

becomes:

```
UniverseVisitor visit_universe{params_};
detail::Initialization tinit;
visit_universe([&local, &tinit](auto&& t) { tinit = t.initialize(local); }, uid);
```

However, this is not done in the PR, as it appears this add 60% overhead to tracking with a single universe type.

2023-09-25 22:46 UTC, sethrj requested changes

2023-09-25 22:46 UTC, sethrj commented on src/orange/univ/UniverseTypeTraits.hh
> +#include "orange/univ/RectArrayTracker.hh"
Replace this with a forward declaration.

2023-09-25 22:46 UTC, sethrj commented on src/orange/univ/UniverseTypeTraits.hh
> + * is a UniverseypeTraits instance.
```suggestion
 * is a UniverseTypeTraits instance.
```

2023-09-25 22:46 UTC, sethrj commented on src/orange/univ/UniverseVisitor.hh
> +#include "UniverseTypeTraits.hh"
You'll need to include both `RectArrayTracker.hh` and `SimpleUnitTracker.hh` here.

2023-09-25 22:46 UTC, sethrj commented on src/orange/univ/UniverseVisitor.hh
> + * Apply a functor to a simple or rect-array universe
```suggestion
 * Apply a functor to a universe tracker of unknown type.
```

2023-09-25 22:46 UTC, sethrj commented on src/orange/univ/UniverseVisitor.hh
> +    ParamsRef params_;
```suggestion
    ParamsRef const& params_;
```

2023-09-25 22:46 UTC, sethrj commented on src/orange/univ/UniverseVisitor.hh
> + * Apply the function to the transform specified by the given ID.
```suggestion
 * Apply the function to the universe specified by the given ID.
```

2023-09-25 22:46 UTC, sethrj commented on src/orange/univ/UniverseVisitor.hh
> + * Apply a functor to a simple or rect-array universe
I realize now there's an inconsistency between our "tracker" name and the "universe" here. I think universe is the abstraction of a unit, rectangular array; and a tracker is the helper class that does the actual navigation/tracking/state update. Just like we have `SurfaceTypeTraits` but `LocalSurfaceVisitor`, maybe rename this class `TrackerVisitor`. Also please add a small unit test.

2023-09-26 00:06 UTC, elliottbiondo commented
@sethrj this should be ready pending CI

2023-09-26 21:02 UTC, sethrj commented
@elliottbiondo I was thinking [the unintentional params copy](https://github.com/celeritas-project/celeritas/pull/959#discussion_r1336451403) could be the source of the 60% slowdown you saw. (Did you look at the occpancy?) After merging, could you please try rerunning maybe a single case with pseudo old vs new on wildstyle to see if the 60% performance regression dissappears?

2023-09-26 21:03 UTC, sethrj approved these changes
Looks great, thanks!

2023-09-26 21:04 UTC, merged

2023-09-26 21:46 UTC, elliottbiondo commented
> @elliottbiondo I was thinking [the unintentional params copy](https://github.com/celeritas-project/celeritas/pull/959#discussion_r1336451403) could be the source of the 60% slowdown you saw. (Did you look at the occpancy?) After merging, could you please try rerunning maybe a single case with pseudo old vs new on wildstyle to see if the 60% performance regression dissappears?

Yep, and this might change the frontier results as well.